#!/usr/bin/env bash
# Build every contract to build/*.wasm, reproducibly.
# The list is DERIVED from the tree, so a new contract is built by existing.
set -euo pipefail
cd "$(dirname "$0")"
kinds=()
for b in */build.sh; do "./$b" "$@"; kinds+=("$(dirname "$b")"); done
[ ${#kinds[@]} -gt 0 ] || { echo "build: no contracts found (*/build.sh matched nothing)" >&2; exit 1; }

# The control builds are not the contracts. They write `<name>.unhardened.wasm`
# and `<name>.remaps-only.wasm` beside the real ones, deliberately built with
# the wrong flags, and a table of their hashes would name numbers no network
# will ever key anything by.
if [ -n "${CONTRACT_BUILD_UNHARDENED:-}${CONTRACT_BUILD_REMAPS_ONLY:-}" ]; then
  echo "build: control build — build/hashes.toml left alone" >&2
  exit 0
fi

# The rev of the tree that compiled, not the rev that happens to be checked
# out: `-dirty` when they can differ. A rev naming a commit whose code is not
# what produced these bytes is a confidently wrong value, and the consumer
# displaying it has no way to tell.
if rev=$(git rev-parse --short HEAD 2>/dev/null); then
  [ -z "$(git status --porcelain 2>/dev/null)" ] || rev="$rev-dirty"
else
  # No git, or not a checkout. "unknown" is a fact; a fabricated rev is not.
  rev=unknown
fi

out=build/hashes.toml
{
  echo "# Generated by ./build.sh. NOT a release: see released.toml."
  echo "#"
  echo "# These are the hashes freenet keys these contracts by — the same digest"
  echo "# that lands in released.toml when an epoch is declared. They are written"
  echo "# here by the one script that builds the wasm, because a consumer that"
  echo "# re-hashes the files itself matches only while its algorithm and its"
  echo "# notion of the canonical wasm stay byte-identical to this one, and shows"
  echo "# an authoritative-looking number that matches nothing when they drift."
  echo "#"
  echo "# Read this file. Never gate on it: it is a record of a build, and a gate"
  echo "# a hash table can satisfy is a gate anyone can edit green."
  echo "rev   = \"$rev\""
  echo "built = \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
  echo
  echo "[code]"
  for k in "${kinds[@]}"; do
    w=build/$k.wasm
    # Derived, never typed — but the name a contract's directory has and the
    # name its wasm gets are two facts, and a mismatch must stop the build
    # rather than quietly leave a contract out of the table.
    [ -f "$w" ] || { echo "build: $k/build.sh produced no $w" >&2; exit 1; }
    echo "$k = \"sha256:$(shasum -a 256 "$w" | cut -d' ' -f1)\""
  done
} > "$out.tmp"
mv "$out.tmp" "$out"
echo "$out: ${#kinds[@]} contract(s) at $rev"
